---
abstract: 'Collects data, counts frequency, and makes up a multi-level counting report'
author:
  - 'Mahiro Ando <mahiro@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Freq
no_index:
  directory:
    - t
    - inc
requires:
  Date::Parse: 1.20
  List::Util: 1.22
  Pod::Usage: 1.36
  Scalar::Util: 1.22
  Test::More: 0.94
version: 0.05
